<a href="https://colab.research.google.com/github/DaewonSeo/Solving_Problems_FutureSkill/blob/main/Pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 퓨처스킬 '판다스 기본' 콘텐츠 문제 풀이 노트북입니다.
[퓨처스킬 '판다스 기본' 바로가기](https://www.futureskill.io/content/903ab63c-2b24-4be0-ba1c-a3ba34dce258) 

In [3]:
import pandas as pd

import numpy as np

df = pd.DataFrame(np.random.normal(size=(5, 4)), columns=list('ABCD'))

In [4]:
df

A         B         C         D
0  2.710606  1.317061 -1.831978  0.866873
1 -0.714555 -1.509175  0.454397 -1.063867
2  0.449187 -0.002033  0.614258  0.523341
3 -0.208608 -1.858322 -0.178396  2.775922
4 -1.244468  1.187269 -0.113739  0.490243

In [5]:
date_index = pd.date_range(start="2020-01-01", end="2020-01-05")

In [6]:
date_index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')

In [7]:
df.index = date_index

In [8]:
df

A         B         C         D
2020-01-01  2.710606  1.317061 -1.831978  0.866873
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-05 -1.244468  1.187269 -0.113739  0.490243

####  Q5. 위에서부터 5개의 행을 출력하는 코드를 작성해보세요.

In [11]:
df.head()

A         B         C         D
2020-01-01  2.710606  1.317061 -1.831978  0.866873
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-05 -1.244468  1.187269 -0.113739  0.490243

#### Q6. 데이터 프레임의 index와 columns, values를 각각 추출해내는 코드를 작성해보세요.

In [14]:
print('데이터 프레임의 인덱스는 : ', df.index)
print('데이터 프레임의 컬럼은 : ', df.columns)
print('데이터 프레임의 값들은 : ', df.values)

데이터 프레임의 인덱스는 :  DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')
데이터 프레임의 컬럼은 :  Index(['A', 'B', 'C', 'D'], dtype='object')
데이터 프레임의 값들은 :  [[ 2.71060564e+00  1.31706079e+00 -1.83197811e+00  8.66873366e-01]
 [-7.14555104e-01 -1.50917514e+00  4.54397163e-01 -1.06386716e+00]
 [ 4.49187440e-01 -2.03327266e-03  6.14258175e-01  5.23340676e-01]
 [-2.08607559e-01 -1.85832226e+00 -1.78395831e-01  2.77592173e+00]
 [-1.24446827e+00  1.18726937e+00 -1.13738979e-01  4.90243497e-01]]


#### Q7. 데이터 프레임의 요약 정보를 출력하는 코드를 작성해보세요.

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2020-01-01 to 2020-01-05
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0 bytes


#### Q8. 데이터 프레임의 전체적인 통계량(통계정보)을 보여주는 코드를 작성해보세요.

In [16]:
df.describe()

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.198432 -0.173040 -0.211092  0.718502
std    1.537456  1.476949  0.969781  1.371315
min   -1.244468 -1.858322 -1.831978 -1.063867
25%   -0.714555 -1.509175 -0.178396  0.490243
50%   -0.208608 -0.002033 -0.113739  0.523341
75%    0.449187  1.187269  0.454397  0.866873
max    2.710606  1.317061  0.614258  2.775922

#### Q9. 데이터 프레임의 컬럼 'C'를 기준으로 내림차순 정렬한 결과를 출력하는 코드를 작성해보세요.

In [20]:
df.sort_values(by=['C'], ascending=False)

A         B         C         D
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-05 -1.244468  1.187269 -0.113739  0.490243
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-01  2.710606  1.317061 -1.831978  0.866873

#### Q10. 데이터 프레임의 컬럼 A(열)을 출력하는 코드를 작성해보세요.

In [21]:
df['A']

2020-01-01    2.710606
2020-01-02   -0.714555
2020-01-03    0.449187
2020-01-04   -0.208608
2020-01-05   -1.244468
Freq: D, Name: A, dtype: float64

#### Q11. 데이터 프레임의 3번째 행의 원소와 index가 '2020-01-05'에 해당하는 행을 출력하는 코드를 작성해보세요.

In [33]:
df.iloc[2]

A    0.449187
B   -0.002033
C    0.614258
D    0.523341
Name: 2020-01-03 00:00:00, dtype: float64

In [35]:
df.loc['2020-01-03']

A    0.449187
B   -0.002033
C    0.614258
D    0.523341
Name: 2020-01-03 00:00:00, dtype: float64

#### Q12. 2020년 1월 2일부터 2020년 1월 4일까지의 데이터 중 컬럼 A,B에 해당하는 데이터를 출력하는 코드를 작성해보세요.

In [40]:
df.loc['2020-01-02':'2020-01-04', ['A', 'B']]

A         B
2020-01-02 -0.714555 -1.509175
2020-01-03  0.449187 -0.002033
2020-01-04 -0.208608 -1.858322

#### Q13. 값 중 0보다 큰 데이터를 모두 출력하는 코드를 작성해보세요.(조건에 해당되지 않아 빈칸일 경우 NaN으로 출력됩니다.)

In [41]:
df[df>0]

A         B         C         D
2020-01-01  2.710606  1.317061       NaN  0.866873
2020-01-02       NaN       NaN  0.454397       NaN
2020-01-03  0.449187       NaN  0.614258  0.523341
2020-01-04       NaN       NaN       NaN  2.775922
2020-01-05       NaN  1.187269       NaN  0.490243

#### Q.14 2개의 데이터 프레임을 이용해서 위 아래로 합쳐진 데이터 프레임을 생성하는 코드를 작성해보세요.

In [42]:
df1 = pd.DataFrame([[1, 3, 5], [2, 4, 6]],
                   columns=['A', 'B', 'C'])

df2 = pd.DataFrame([[-1, -3, -5], [-2, -4, -6]],
                   columns=['A', 'B', 'C'])

In [51]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [52]:
df_merged

A  B  C
0  1  3  5
1  2  4  6
2 -1 -3 -5
3 -2 -4 -6

#### Q15. 양옆으로 합쳐진 데이터 프레임을 생성하는 코드를 작성해보세요.

In [57]:
df_merged_across = pd.concat([df1, df2], axis=1)

In [58]:
df_merged_across

A  B  C  A  B  C
0  1  3  5 -1 -3 -5
1  2  4  6 -2 -4 -6

Q.16 csv 파일 불러오기

In [59]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [61]:
df = pd.read_csv('train.csv')

### Q17. excel 파일의 특정 sheet 불러오기

In [64]:
from google.colab import files
uploaded = files.upload()

Saving report.xlsx to report.xlsx


In [65]:
df = pd.read_excel('report.xlsx', sheet_name='report')

#### Q18. csv 수정 후 저장하기

In [67]:
df = pd.read_csv('train.csv')

In [70]:
df = df.loc[:, 'PassengerId': 'Embarked']

In [73]:
df.to_csv('train(edited).csv', index=False)