<a href="https://colab.research.google.com/github/DaewonSeo/Solving_Problems_FutureSkill/blob/main/Pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

import numpy as np

df = pd.DataFrame(np.random.normal(size=(5, 4)), columns=list('ABCD'))

In [ ]:
date_index = pd.date_range(start="2020-01-01", end="2020-01-05")

In [ ]:
date_index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.index = date_index

In [ ]:
df

A         B         C         D
2020-01-01  2.710606  1.317061 -1.831978  0.866873
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-05 -1.244468  1.187269 -0.113739  0.490243

####  Q5. 위에서부터 5개의 행을 출력하는 코드를 작성해보세요.

In [ ]:
df.head()

A         B         C         D
2020-01-01  2.710606  1.317061 -1.831978  0.866873
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-05 -1.244468  1.187269 -0.113739  0.490243

#### Q6. 데이터 프레임의 index와 columns, values를 각각 추출해내는 코드를 작성해보세요.

In [ ]:
print('데이터 프레임의 인덱스는 : ', df.index)
print('데이터 프레임의 컬럼은 : ', df.columns)
print('데이터 프레임의 값들은 : ', df.values)

데이터 프레임의 인덱스는 :  DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05'],
              dtype='datetime64[ns]', freq='D')
데이터 프레임의 컬럼은 :  Index(['A', 'B', 'C', 'D'], dtype='object')
데이터 프레임의 값들은 :  [[ 2.71060564e+00  1.31706079e+00 -1.83197811e+00  8.66873366e-01]
 [-7.14555104e-01 -1.50917514e+00  4.54397163e-01 -1.06386716e+00]
 [ 4.49187440e-01 -2.03327266e-03  6.14258175e-01  5.23340676e-01]
 [-2.08607559e-01 -1.85832226e+00 -1.78395831e-01  2.77592173e+00]
 [-1.24446827e+00  1.18726937e+00 -1.13738979e-01  4.90243497e-01]]


#### Q7. 데이터 프레임의 요약 정보를 출력하는 코드를 작성해보세요.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2020-01-01 to 2020-01-05
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0 bytes


#### Q8. 데이터 프레임의 전체적인 통계량(통계정보)을 보여주는 코드를 작성해보세요.

In [ ]:
df.describe()

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.198432 -0.173040 -0.211092  0.718502
std    1.537456  1.476949  0.969781  1.371315
min   -1.244468 -1.858322 -1.831978 -1.063867
25%   -0.714555 -1.509175 -0.178396  0.490243
50%   -0.208608 -0.002033 -0.113739  0.523341
75%    0.449187  1.187269  0.454397  0.866873
max    2.710606  1.317061  0.614258  2.775922

#### Q9. 데이터 프레임의 컬럼 'C'를 기준으로 내림차순 정렬한 결과를 출력하는 코드를 작성해보세요.

In [ ]:
df.sort_values(by=['C'], ascending=False)

A         B         C         D
2020-01-03  0.449187 -0.002033  0.614258  0.523341
2020-01-02 -0.714555 -1.509175  0.454397 -1.063867
2020-01-05 -1.244468  1.187269 -0.113739  0.490243
2020-01-04 -0.208608 -1.858322 -0.178396  2.775922
2020-01-01  2.710606  1.317061 -1.831978  0.866873

#### Q10. 데이터 프레임의 컬럼 A(열)을 출력하는 코드를 작성해보세요.

In [ ]:
df['A']

2020-01-01    2.710606
2020-01-02   -0.714555
2020-01-03    0.449187
2020-01-04   -0.208608
2020-01-05   -1.244468
Freq: D, Name: A, dtype: float64

#### Q11. 데이터 프레임의 3번째 행의 원소와 index가 '2020-01-05'에 해당하는 행을 출력하는 코드를 작성해보세요.

In [ ]:
df.iloc[2]

A    0.449187
B   -0.002033
C    0.614258
D    0.523341
Name: 2020-01-03 00:00:00, dtype: float64

In [ ]:
df.loc['2020-01-03']

A    0.449187
B   -0.002033
C    0.614258
D    0.523341
Name: 2020-01-03 00:00:00, dtype: float64

#### Q12. 2020년 1월 2일부터 2020년 1월 4일까지의 데이터 중 컬럼 A,B에 해당하는 데이터를 출력하는 코드를 작성해보세요.

In [ ]:
df.loc['2020-01-02':'2020-01-04', ['A', 'B']]

A         B
2020-01-02 -0.714555 -1.509175
2020-01-03  0.449187 -0.002033
2020-01-04 -0.208608 -1.858322

#### Q13. 값 중 0보다 큰 데이터를 모두 출력하는 코드를 작성해보세요.(조건에 해당되지 않아 빈칸일 경우 NaN으로 출력됩니다.)

In [ ]:
df[df>0]

A         B         C         D
2020-01-01  2.710606  1.317061       NaN  0.866873
2020-01-02       NaN       NaN  0.454397       NaN
2020-01-03  0.449187       NaN  0.614258  0.523341
2020-01-04       NaN       NaN       NaN  2.775922
2020-01-05       NaN  1.187269       NaN  0.490243

#### Q.14 2개의 데이터 프레임을 이용해서 위 아래로 합쳐진 데이터 프레임을 생성하는 코드를 작성해보세요.

In [ ]:
df1 = pd.DataFrame([[1, 3, 5], [2, 4, 6]],
                   columns=['A', 'B', 'C'])

df2 = pd.DataFrame([[-1, -3, -5], [-2, -4, -6]],
                   columns=['A', 'B', 'C'])

In [ ]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df_merged

A  B  C
0  1  3  5
1  2  4  6
2 -1 -3 -5
3 -2 -4 -6

#### Q15. 양옆으로 합쳐진 데이터 프레임을 생성하는 코드를 작성해보세요.

In [ ]:
df_merged_across = pd.concat([df1, df2], axis=1)

In [ ]:
df_merged_across

A  B  C  A  B  C
0  1  3  5 -1 -3 -5
1  2  4  6 -2 -4 -6

Q.16 csv 파일 불러오기

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
df = pd.read_csv('train.csv')

### Q17. excel 파일의 특정 sheet 불러오기

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving report.xlsx to report.xlsx


In [ ]:
df = pd.read_excel('report.xlsx', sheet_name='report')

#### Q18. csv 수정 후 저장하기

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df = df.loc[:, 'PassengerId': 'Embarked']

In [ ]:
df.to_csv('train(edited).csv', index=False)

#### Q19. missing value 처리하기

In [2]:
from google.colab import files
uploaded = files.upload()

Saving toy.xlsx to toy.xlsx


In [24]:
df_c = pd.read_excel('toy.xlsx')

In [35]:
df_c

A    B     C
0  1.0 -1.0   2.0
1  2.0  NaN   3.0
2  3.0 -3.0   4.0
3  4.0 -4.0   7.0
4  5.0  NaN   NaN
5  NaN -6.0  10.0

In [7]:
df_new_c = df_c.dropna()

In [8]:
df_new_c

A    B    C
0  1.0 -1.0  2.0
2  3.0 -3.0  4.0
3  4.0 -4.0  7.0

#### Q20. missing value 위의 같은 열의 윗 행 값으로 채워보기

In [15]:
df_c_fill_na = df_c.fillna(method="ffill")

In [16]:
df_c_fill_na

A    B     C
0  1.0 -1.0   2.0
1  2.0 -1.0   3.0
2  3.0 -3.0   4.0
3  4.0 -4.0   7.0
4  5.0 -4.0   7.0
5  5.0 -6.0  10.0

#### Q21. missing value를 해당 열의 평균 값으로 대체하는 방법으로 처리하는 코드를 작성해보세요

In [45]:
df_c_fill_mean = df_c.fillna(df_c.mean().mean())

In [46]:
df_c_fill_mean

A         B          C
0  1.000000 -1.000000   2.000000
1  2.000000  1.566667   3.000000
2  3.000000 -3.000000   4.000000
3  4.000000 -4.000000   7.000000
4  5.000000  1.566667   1.566667
5  1.566667 -6.000000  10.000000

Q23. aggregating

In [47]:
df_23 = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                      'B': [-1, -2, -3, -4, -5],
                      'C': [2, 3, 4, 7, 8]})

In [51]:
df_23['평균'] = df_23.mean(axis=1)

In [52]:
df_23

A  B  C        평균
0  1 -1  2  0.666667
1  2 -2  3  1.000000
2  3 -3  4  1.333333
3  4 -4  7  2.333333
4  5 -5  8  2.666667

#### Q24. 각 열의 합계를 맨 마지막 행에 추가하는 코드를 작성해보세요.

In [63]:
df = pd.DataFrame([[1,-1,2],
                   [2,-2,3],
                   [3,-3,4],
                   [4,-4,7],
                   [5,-5,8]], columns=list('ABC'))

In [64]:
df['평균'] = df.mean(axis=1)

In [65]:
df.loc[5] = df.sum()

In [66]:
df

A     B     C        평균
0   1.0  -1.0   2.0  0.666667
1   2.0  -2.0   3.0  1.000000
2   3.0  -3.0   4.0  1.333333
3   4.0  -4.0   7.0  2.333333
4   5.0  -5.0   8.0  2.666667
5  15.0 -15.0  24.0  8.000000

#### Q25. aggregating 3

In [68]:
df = pd.DataFrame([[1, -1, 2, 'A'],
                  [2, -2, 3, 'A'],
                  [3, -3, 4, 'B'],
                  [4, -4, 7, 'B'],
                  [5, -5, 8, 'B']], columns=['val1', 'val2', 'val3', 'label'])

In [69]:
df 

val1  val2  val3 label
0     1    -1     2     A
1     2    -2     3     A
2     3    -3     4     B
3     4    -4     7     B
4     5    -5     8     B

In [70]:
df.groupby('label').sum()

val1  val2  val3
label                  
A         3    -3     5
B        12   -12    19

#### Q26. 특정 컬럼을 기준으로 피벗 테이블 생성하는 코드를 작성해보세요

In [74]:
df_pivot_table = pd.pivot_table(df, index=['label'])

In [75]:
df_pivot_table

val1  val2      val3
label                      
A       1.5  -1.5  2.500000
B       4.0  -4.0  6.333333

In [76]:
df.groupby('label').mean()

val1  val2      val3
label                      
A       1.5  -1.5  2.500000
B       4.0  -4.0  6.333333